sonar.projectKey=ARSW2026-JDC_Traffic-Simulator-Gateway
sonar.organization=arsw2026-jdc
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/tests/**,node_modules/**
sonar.coverage.exclusions=**/*.test.ts,**/tests/**