name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm ci

      - name: Build proyecto
        run: npm run build

      - name: Empaquetar app
        run: tar -czf app.tar.gz dist package.json package-lock.json

      - name: Copiar a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "~/gateway"

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/gateway

            # limpiar build anterior
            rm -rf dist

            # descomprimir nueva versión
            tar -xzf app.tar.gz

            # instalar solo prod deps (más rápido)
            npm ci --omit=dev

            # reiniciar app
            pm2 restart gateway || pm2 start dist/index.js --name gateway

            pm2 save